export const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING'
export const FETCH_MOVIES_SUCCEEDED = 'FETCH_MOVIES_SUCCEEDED'
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED'

export const FETCH_MOVIE_PENDING = 'FETCH_MOVIE_PENDING'
export const FETCH_MOVIE_SUCCEEDED = 'FETCH_MOVIE_SUCCEEDED'
export const FETCH_MOVIE_FAILED = 'FETCH_MOVIE_FAILED'